services:
  - type: web
    name: widechat-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: GOOGLE_DRIVE_CREDENTIALS
        sync: false
